### ISSUE TITLE
How do we incorporate ImageStacks with NaNs in the data

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#1367]
Problem: One possible way to support ragged `ImageStack` objects where the cardinality of rounds/ch/zplanes are not consistent is to create the full 5D tensor, but fill the missing values with `NaN`.

One possible approach:

1. Prior to any transform/apply operation, we create a mask of all the `NaN`s in the original data. 
2. Zero out all the values (or assume the average value of the nearest non-NaN neighbors?).
3. Perform the transform/apply, and then replace the output pixels with `NaN` from the mask generated in (1).

**Comment by dganguli** [comment]
This is deeply complicated. For image processing algorithms (e.g., filtering, and segmentation) in an ideal world, we would adopt the same NaN handling behavior that the current algorithms we wrap do. However, at times, these libraries themselves struggle with what to do here. 

See for example a recent skimage discussion: https://github.com/scikit-image/scikit-image/issues/1624

For a different example, see how astropy handles NaNs for convolution: http://docs.astropy.org/en/stable/convolution/

In general, creating a mask of NaNs, imputing NaNs to have some value (e.g., 0 or some nearest neighbor fit), followed by filtering, then replacement of the imputed values back with NaNs is sketchy at best.

For operations that are ImageStack -> IntensityTable (decoding), or subsequent operations that are IntensityTable -> IntensityTable or other (for doing QC or interrogating spots), this is a much easier problem to solve. For decoding, I suggest we simply do not decode pixel traces with NaN values. For QC or other interrogation tasks, we leave it up to the user for how to handle this, since we're approaching out of scope for Starfish territory.

My suggestion is to first understand how our wrapped calls to skimage handle NaNs. Second, if users are loading ImageStacks with NaNs, we may want to simply push NaN handling back to the user, since they understand their NaNs the best. Thirdly, we can avoid NaNs all together by adopting an ImageStack as a dictionary of numpy arrays approach. That way you never have to full out a 5D tensor and handle missing values yourself.

@freeman-lab and @sofroniewn may have some further insight here.

**Comment by ttung** [comment]
The issue is that if we are going to support ragged arrays in `ImageStack`, we have to put something there (and `NaN` does seem like the most reasonable thing to have there).

The alternative is to make `ImageStack` aware of which tiles are nonexistent (nothing but `NaN`), and explicitly not process those tiles.  For the sporadic `NaN` that the user is introducing, we balk.

**Comment by ttung** [comment]
Conclusion of @dganguli and my out-of-band conversation:

ImageStack needs to keep track of which tiles are nonexistent, and skip operations on them.

**Comment by dganguli** [comment]
Yeah @dganguli thought we were talking about individual pixel values, within a tile, that are NaN. That's hard. But @ttung is asking what to do when entire tiles are NaN. Which is simple, just ignore them in apply/transform operations.

**Comment by ttung** [comment]
We are not going to support this model.  We will instead steer users towards loading data by round.
