### ISSUE TITLE
Script to rename starfish output files to match HCA DCP ingest requirements. 

### ISSUE THREAD

**Issue by zperova** [spacetx/starfish#1443]
As an HCA DCP wrangler, I would like to have an ability to rename starfish output files in bulk to match ingest requirements to enable submission of imaging datasets to the DCP.

Contributors tend to store files in a directory structure where the top folder is named by the imaged_specimen ID and contains all the Starfish output files. 
For example: 
Folder `Image_specimen_01` contains files: `experiment.json`, `codebook.json`, `dots-fov-00.json`, `dots-fov_000-Z0-H0-C0.tiff`, etc
Folder `Image_specimen_02` contains files: `experiment.json`, `codebook.json`, `dots-fov-00.json`, `dots-fov_000-Z0-H0-C0.tiff`, etc

HCA DCP ingest does not support directories (yet?) and thus requires the files to have unique names within a project (until adding data to an existing project is implemented).

Thus the starfish output files need to be renamed (to append the folder name, for example) and on top of that all the manifests within the folders have to be changed to point to the correct names of the files. This is currently a blocker for ingestion.

Could this be put into a script that a wrangler/contributor can run?

**Comment by zperova** [comment]
@ttung could you please help with this?

**Comment by ambrosejcarr** [comment]
Hey @zperova, I'm noting here for posterity the suggestions from the previous starfish sync: 

We suspect problem is best addressed by the HCA Data Store or the SpaceTx-Format, rather than a flattening script. To figure out how this can be approached, could you figure out if there is a data store engineer working on these problems? We're happy to chat with them to figure out the right way forward here!
