### ISSUE TITLE
Starfish should accept codebooks uneven number of channels across rounds 

### ISSUE THREAD

**Issue by shanaxel42** [spacetx/starfish#1483]
(see below for user story - @neuromusic )

**Comment by berl** [comment]
I was in the middle of writing up an issue on this as a `"user_story"`:
**As a**  _starfish user with a multiplexed assay_,
**I want**  _to be able to decode experiments without arbitrary constraints on my codebook_  **so that**  _analysis data structures don't negatively impact my data acquisition_.

### Acceptance Criteria

1. If I have an  `Experiment` with barcoded data distributed through any `(r,c)`, 
1. I should be able to pass a list of `(r,c)` tuples of length `N_bits` and a codebook with `N_bits`  to any decoder and have it successfully decode because the size of the codewords is the same as the number of `(r,c)` tuples

**Comment by ambrosejcarr** [comment]
@shanaxel42 and I had a discussion about whether IntensityTable is the right _input_ for decoding, given this issue. There are a few options: 

1. It's the right structure! we put `np.NaN` anywhere that's not intended to contribute to a code and validate that the codebase properly respects NaN objects. This is probably the most flexible way, since one could feasibly decode a codebook that has codes of different lengths. 
2. We use a 2D dataframe or xarray with shape `(targets, bits)` and `bits` has a multiindex (or pair of coordinates) composed of `(round, channel)` information
3. We use a 2D compressed-sparse row matrix that's organized as above. This likely requires more language improvements to the python sparse library as these data structures can't interface with sklearn's `NearestNeighbors`

**Comment by neuromusic** [comment]
@shanaxel42 landed this in #1626
