### ISSUE TITLE
Add validate-sptx fuzz command

### ISSUE THREAD

**Issue by joshmoore** [spacetx/starfish#513]
cF: https://github.com/spacetx/sptx-format/pull/21

Approximate output:

```
validate_sptx/test_field_of_view.py::test_fuzz_input[0] 0    corrupt     b'{\n'
validate_sptx/test_field_of_view.py::test_fuzz_input[1] 1    invalid     b'  "version": "0.0.0",\n'
validate_sptx/test_field_of_view.py::test_fuzz_input[2] 2    invalid     b'  "fov": 0,\n'
validate_sptx/test_field_of_view.py::test_fuzz_input[3] 3    corrupt     b'  "dimensions": [\n'
validate_sptx/test_field_of_view.py::test_fuzz_input[4] 4    passes      b'      "x",\n'
validate_sptx/test_field_of_view.py::test_fuzz_input[5] 5    passes      b'      "y",\n'
validate_sptx/test_field_of_view.py::test_fuzz_input[6] 6    passes      b'      "z",\n'
validate_sptx/test_field_of_view.py::test_fuzz_input[7] 7    passes      b'      "r",\n'
validate_sptx/test_field_of_view.py::test_fuzz_input[8] 8    corrupt     b'      "c"\n'
validate_sptx/test_field_of_view.py::test_fuzz_input[9] 9    corrupt     b'  ],\n'
...
```

**Comment by joshmoore** [comment]
Someone feel free to assign this to me.

**Comment by ambrosejcarr** [comment]
After the basic fuzz test is done, I would be extra pleased if it could be amended to sniff out common JSON errors that result from line deletions and tries to guess a fix for them so that it can get more lines as `invalid` or `passes` instead of `corrupt`. 

For example, the difference between 
`validate_sptx/test_field_of_view.py::test_fuzz_input[8] 8    corrupt     b'      "c"\n'`
and 
`validate_sptx/test_field_of_view.py::test_fuzz_input[8] 8    passes     b'      "c"\n'`
could be important, and probably hinges on the fact that there is now a trailing comma on line 7.

Conversely, I don't care much that line 9 is corrupt.  I leave to you to judge the relative difficulty of this -- feel free to ignore, just wanted to point out it would be useful :)

**Comment by joshmoore** [comment]
>  I would be extra pleased if it could be amended to sniff out common JSON errors that result from line deletions and tries to guess a fix for them so that it can get more lines as invalid or passes instead of corrupt

My current assumption is that it will make more sense to work on the JSON tree as opposed to the line-based representation.
