### ISSUE TITLE
Evaluate and switch to jupytext

### ISSUE THREAD

**Issue by ttung** [spacetx/starfish#535]
[edit, link: [https://towardsdatascience.com/introducing-jupytext-9234fdff6c57?gi=5c72bd703114](https://towardsdatascience.com/introducing-jupytext-9234fdff6c57?gi=5c72bd703114)]

**Comment by neuromusic** [comment]
after conversation w/ @kne42, sphinx-gallery #934 is probably a better solution - @ambrosejcarr

**Comment by kne42** [comment]
To clarify, `jupytext` is an awesome tool for development reasons (primarily because it makes it easy to `git` diff and IDEs can parse it more easily when refactoring) but `sphinx-gallery` is much better if you just want something for documentation purposes. If I were to use `jupytext` in this project it would be to replace all the `.ipynb`s with `.py`s.

**Comment by ttung** [comment]
Oh, I remember this more clearly now.  This was supposed to replace `nbencdec`.  I think if we junk all the notebooks (I think that's the goal), we won't need either.
