### ISSUE TITLE
Experiment.from_json() on a "single-fov experiment" yields uninformative error

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#614]
Calling from_json() on an `experiment.json` where the `primary_images.json` is directly linked to the `experiment.json` instead of through a `manifest.json` intermediary yields the following uninformative error message: 

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-fe0a85d3077c> in <module>()
      3 
      4 experiment_json = os.path.expanduser('~/Downloads/BaristaSeq/files_and_metadata/experiment.json')
----> 5 Experiment.from_json(experiment_json)

~/projects/spacetx/starfish/starfish/experiment/experiment.py in from_json(cls, json_url)
    185 
    186         fovs: MutableSequence[FieldOfView] = list()
--> 187         for fov_name, primary_tileset in primary_image.all_tilesets():
    188             aux_image_tilesets_for_fov: MutableMapping[str, TileSet] = dict()
    189             for aux_image_type, aux_image_collection in auxiliary_images.items():

AttributeError: 'TileSet' object has no attribute 'all_tilesets'
```

We should: 
- [ ] validate this aspect of experiment 
- [ ] throw an error if this validation fails. 

Related to #524

**Comment by joshmoore** [comment]
I think the strict setting of gh-538 would have slightly improved this UX, since before this exception was thrown a warning would have been printed with the specific problem. To improve on that one would need to:

 * add a lazy-loading option for strict validation such that data isn't pre-loade (too slow)
 * perhaps make lazy-loading strict-validation the default (no user action needed)
 * modify validate_sptx to not (always) use `warnings` but instead throw friendly exceptions
