### ISSUE TITLE
Improve our glossary

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#714]
@zperova and @hewgreen identified that our experiment has a bit more flexibility than we'd like users to take advantage of. For example, user could create an `experiment.json` from two totally distinct tissues, like lung and brain, or from multiple patients, so long as they leveraged the same codebook. 

Internally, I believe we envision users creating separate `experiment.json` objects per tissue sample, and this separation will be _required_ by the HCA.

To solve this, we had discussed restructuring the `glossary.md` file to have a logical order. It would be even clearer if we could include in the glossary a diagram that relates the different terms to one another, as a visual diagram may reduce confusion. 

The implementation could show an experiment encompassing a tissue slice, broken up into fields of view by the size of the microscope sensor. The coordinates in both pixel space and physical space could be overlaid on top to illustrate their differences, and a stack of images could be used to represent the multiplicity of rounds and channels. 

The diagram, as described, would lead people towards formulations of our metadata that are best supported by starfish. 

cc @joshmoore @dganguli @ttung @shanaxel42

**Comment by hewgreen** [comment]
A bit about why

> this separation will be required by the HCA

Defining experiment.json at the level of 'a sample under the microscope' very explicitly seems to be the rough consensus but if we pinned it down I can foresee these consequences. Please add or comment on this list.

**Pro's**
This is the same level of granularity that the HCA metadata records. So this would enable us to link each `sample under the microscope` (we call it `imaged specimen`) explicitly to an experiment.json manifest.

Keeping this one to one means we never loose mapping to the metadata about the sample.

**Con's**
We loose further granularity of indexed metadata. For example, if a chuck was imaged in two distinct places that may have different anatomy labels, we would only be able to provide a list of those two values to a user browsing datasets. We would need to link at the level of FOV_manifest.json within the spacetx metadata (again one to one) in order to support more granular intra sample metadata. We tentatively don't think this is a requirement at the moment https://github.com/spacetx/starfish/issues/715.
