### ISSUE TITLE
Documentation Improvements 

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#858]
Note on documentation types: https://www.divio.com/blog/documentation/

**Comment by neuromusic** [comment]
Here's my proposal for the documentation refactor. Open to discussion.

### landing page

Refactor the landing page to facilitate users quickly getting to the places they need to be. I like the seaborn documentation structure:

- A short block of text describing starfish and linking people to specific places in the documentation
- A "contents" list which provides top level navigation to key pages of the documentation
- A "Features" list which provides links to the API and examples/vignettes for each major feature of the package

### Contents

The contents list would contain the following links

- Introduction (an introduction to the motivation for the package and a the key value proposition)
- Installation (how to install starfish, including how to use conda/virtualenv)
- Data Standard (the SpaceTx Image Format Specification)
- *Tutorial* (series of vignettes walking a user through the process of creating a pipeline)
- Examples (link to a gallery of vignettes/examples of using starfish, generated with Sphinx-gallery)
- Command Line (documentation on using the CLI)

### Features

This section would highlight key sections of the API documentation

- Filtering
- Spot-Finding
- Decoding
- Segmenting
- Pipelining

### Tutorial

One need for SpaceTx users is an end-to-end tutorial so that users can create a pipeline recipe. This will be a series of vignettes demonstrating the use of the API

0. Is this for me? (what assays does this support?)
1. Getting data into SpaceTx (needs to be aligned and corrected)
2. Filtering (how to select filter parameters. w/ napari?)
3. Spot-finding (how to select spot-finding parameters. w/ napari?)
4. Decoding (how to select decoding parameters)
5. Segmenting
6. Creating a pipeline recipe
7. Running a pipeline on an experiment
8. Collecting the results of an experiment

**Comment by ambrosejcarr** [comment]
I will go over your proposal in detail. In the mean time, reviewing PRs reminds me that we will need some better documentation for our main objects, orthogonal to the usage workflow. 

`IntensityTable`, `Codebook`, and `ExpressionMatrix` are easier as we can point at external documentation, but we've heard from @berl and @kevinyamauchi that xarray is not very intuitive. It took our team a while to learn their indexing as well, so something that captures:
1.  Where to find [detailed information](http://xarray.pydata.org/en/stable/indexing.html) on how to index things
2. How to use `xarray` indexing to do some simple things like slice out a channel, or do a max projection. Should include translations of their operations into our object model. For example, we leverage label-based indexing using the `Indices` and `Features` types. 
3. How to escape and get a `numpy` array that supports numerical indexing, if all else fails. 

For ImageStack we'll need to build something similar to  from the ground up. 

This will need to be done for whatever we arrive at for `Segmentation[Mask|Polygon]` as well.

**Comment by neuromusic** [comment]
> How to escape and get a numpy array that supports numerical indexing, if all else fails.

🤣

**Comment by ttung** [comment]
I would make tutorials for the various audiences: CLI users, API users, algorithm developers.

**Comment by ambrosejcarr** [comment]
@shanaxel42 Adding some notes on where I think the documentation can be improved upon. I ended up skimming through the whole docs instead of just the API docs. I can pick some of the stuff towards the bottom of the list. 

I'd also like to raise some general questions about our UX that I think would be worth working out. For example, what prefix should users expect to be able to tab complete to:

1. load an object (e.g. `load_`, `from_` both used)
2. save an object (`save_` and `to_` both used)
3. convert an object to another form (`to_` most common here)

Do we want the most common constructor and save methods to just be `load` and `save` or should we be specific about what types of files? Should `save` and `load` take a format parameter and attempt to guess based on file extensions? Some of our methods already do this to some extent (e.g. `ImageStack.from_path_or_url`)

Do we want to try to make our custom classes conform to standard container types for ease of use and intuitiveness? If so, which objects for which classes? 

It would be good to apply these decisions across the code base when we've decided. In the below objects, I've made some suggestions assuming we picked `load_`, `save_`, and `to_` for loading, saving, and converting, respectively, but recognize we may decide otherwise. 

# General comments

- Our objects doc their return types twice. Once in `returns` and once in `Return Type`. These do not always agree (see e.g. `ImageStack.max_proj`)
- We have some examples. It's probably a good idea to transform them into doctests so we verify they continue to work across refactors. 
- Kevin was mostly concerned about intensitytable and codebook when he said the following (which I will do) but I think this sentiment probably applies generally: 

> In general, there is a lot of nomenclature that I think needs to be defined. Currently, I find a lot of the docstrings for the methods difficult to understand. For example: `Codebook.decode_per_round_max`: decode each feature by selecting the per-imaging-round max-valued channel) -> I'm not sure what per-imaging-round-max-valued channel means, so it's not clear exactly what this method does.

- we probably have more public methods than we need, As a rule of thumb, it could make sense to make parts of the API private that aren't used in the vignettes? 

# Specific objects

## Experiment

Could use a top-level summary about the object. Specifically: 

- It's not clear in the API docs that this is the top-level starfish object, or what users might want to do with it. 
- Rename `from_json` to `load` to match the rest of our objects? 
- No description of codebook or its importance
- No suggestions about how a user might want to interact with this object or references to spaceTx format.  (e.g. why would one have an experiment.json)

## FieldOfView

This one is much better, there are a few changes I'd suggest: 

- I think upper-case `PRIMARY_IMAGES` will fail, need to be clear that's an enum. 
- I might renamed `iterate_image_type` to `iter_images`, since it's clear that it takes an `image_type` from the parameters. 

## ImageStack

- shape/raw_shape docs aren't that informative (you need to read the return calls)
- apply: needs examples
- export: rename to `save` to match the API of the rest of our objects? The parameters of export are totally unclear to me. I just use it with defaults and it works, but I always assume something's going to fail here. :-)
- related, might make sense to update `to_multipage_tiff` to `save_multipage_tiff` and doc the save/load methods that are public together. 
- should all the constructors be public? `from_tileset`? `from_path_or_url` feels like a candidate for "load" to me.
- transform is a super cool method that deserves some examples

## Codebook

- I'll handle methods, but generally it looks like we're docing the attributes from the underlying DataArray object. Some of these aren't very pretty. Dunno what to do here but I bet you could think of something that's nicer than we have. :-)

## PipelineComponent

- This probably should go elsewhere (it's more developer facing)

## Filtering
- Looks like none of the run methods for our filters (or pipeline components) are doc'd

## Deconvolution
- Richardson-Lucy has a heading but no docs

## Decoding
- This section links to nothing (and I think has been removed from the codebase in favor of the Codebook)

## Spot Finding
- The SpotFinders are not rendering their class docstrings. 

## Types
- Features is pretty gross and would love to hear @ttung 's suggestions about how we could improve these enum values. 

## SpotAttributes
- out of date, is really just an intermediate file for some of our spot finders. I might remove it from the docs; users will never pass these types, it's just used for our API contracts. 

## Validators
- Missing some method docs. 

## Config
- should probably describe what each of the properties we support do and why someone might want to change them (e.g. `strict`). 

## Provenance Logging
- Is actually pretty great! No comments here. 

## Input Formats
- would prefer the table of contents render and then the text is below, instead of needing to click through links which contain _only_ TOCs, but the content here is good enough for now. 

## Citation
- we should add @kne42 

## License
- should update copyright to 2019. 

## Contributing
- looks like it's written with markdown syntax and being rendered in .rst (e.g. code blocks are naked backticks with no :code: role. )

## Data formatting examples
- should be separate pages which directly include the examples instead of requiring click-through

## Data processing examples
- same as above.

**Comment by neuromusic** [comment]
looking to the rest of the pydata ecosystem...

- pandas uses `read_*` for loading and `to_*` for saving AND conversion http://pandas.pydata.org/pandas-docs/stable/user_guide/io.html
- xarray uses `open_*` for loading and `to_*` for saving AND conversion http://xarray.pydata.org/en/stable/io.html
- numpy uses `load*` for loading and `save*` for saving and `to*` for conversion (I think this is largely inherited from Matlab practices) https://docs.scipy.org/doc/numpy/reference/routines.io.html

My vote would be to conform to **xarray** standards here, since that is the library we are building upon.

**Comment by neuromusic** [comment]
much of the discussion in this issue is out of date. I'm going to close this in favor of a clean epic to track the documentation improvements we're working on in the coming weeks.
