### ISSUE TITLE
ease pinned requirements to facilitate installation for users

### ISSUE THREAD

**Issue by neuromusic** [spacetx/starfish#932]
Currently, _starfish_ specifies it's dependencies like so:

1. we specify requirements with loose dependencies in `REQUIREMENTS.txt.in` 
2. a dev uses `make REQUIREMENTS.txt` to dump the `pip freeze` to `REQUIREMENTS.txt`, which gets committed
3. `REQUIREMENTS.txt` with hard-pinned dependencies gets scooped up into `setup.py`

This results in two things that are not ideal for users.

First, users are forced to install packages which are needed for development, but not for use of the package, such as sphinx and pytest.

Second, by including hard pinned versions in setup.py, pip will aggressively force their environment to match the pinning. This may result in users unable to install _starfish_ due to conflicts with other packages, or (if users are using conda environments) multiple versions of dependent packages installed.

To alleviate these issues, I have two proposals:

First, limit the primary "REQUIREMENTS.txt" file to those requirements needed to *use* starfish, then split off requirements for development (e.g., pytest for local testing and CI) and building documentation (sphinx & viz packages) into a separate requirements files for dev and docs: `REQUIREMENTS-dev.txt` and `REQUIREMENTS-docs.txt`. We can point travis and readthedocs at these files for building the environments for tests and docs. We can use pip's `-r` in these files to inherit the core dependencies from `REQUIREMENTS.txt`.

Second, we should carefully consider the exact packages that need strict pinning for users and limit the hard pinning to the smallest set of packages we can. For example, @ttung emphasized that numpy & scikit-image need hard pins. We should also consider keeping the list of dependencies in `REQUIREMENTS.txt` separate from those in `setup.py`, using `setup.py` to (a) specify hard pins and (b) any packages critical for starfish to work. This distinction may allow us to be more strict with the pinning in `REQUIREMENTS.txt`, as it becomes "this is a description of the environment that we test against" rather than "this is the environment that users must use".

Would love to hear thoughts on this proposal.

**Comment by neuromusic** [comment]
"how do we get the docs building again in the short term" -> https://github.com/spacetx/starfish/pull/733#discussion_r229084779

**Comment by neuromusic** [comment]
I think one of the key differences here as compared with Nov 9 is a separate `REQUIREMENTS-DOCS.txt` & implementing inheritance with `-r` to prevent repetition in specifying dependencies.

**Comment by ambrosejcarr** [comment]
I have a situation where there are two packages that I am either actively contributing to (`skimage`) or contributing feature requests that are getting developed rapidly (`napari`). I need features faster than they make releases, so I need a solution that allows me to install these packages from either (1) a pinned master commit or (2) current master.

I am willing to take on the burden of *immediately* fixing the build when changes to skimage breaks our tests. 
I am willing to commit to making *timely* fixes to napari, (napari errors will not break our core pipelines). 

Because of the complexity of our installation scheme, I am blocked on merging 3 PRs to master that contain pipeline components or visualization improvements, and blocked from initiating work on unifying spot detection.

**Comment by neuromusic** [comment]
I think it's a bad idea to make releases that have dependencies on pre-release code.

Q for @ttung @shanaxel42 @kne42: Are we making the assumption that anything in master *could* be released?

If so & if we agree on my first statement, I'd say that your changes need to wait for a skimage release or live on a development fork.

**Comment by kne42** [comment]
Things on master are supposed to not break. However, they are not guaranteed to be stable either.

If you need specific features from `scikit-image`, I would recommend manually porting the code from them into a `compat.py` file like so:
```python
import skimage


if [int(v) for v in skimage.__version__.split('.')] <= (0, 14, 2):  # version of scikit-image at the time of backporting this
    def foo():
        """This is a direct copy of what scikit-image has.
        """
else:
    foo = skimage.foo
```

`napari-gui` is a bit more tricky since our code is object-oriented and so, features cannot be similarly isolated. With a normal project, installing from source should still be considered relatively safe; however, since we have made it very clear that we will have breaking changes on source and release, pinning is recommended. When `napari-gui` is updated, you should make the corresponding changes to your codebase and pin the new version. This process should continue until `napari-gui` adopts a deprecation cycle.

**Comment by ambrosejcarr** [comment]
Ok, monkey patching for skimage it is. Thanks. 

I guess I'll just press for releases on napari. :-)

**Comment by ttung** [comment]
I personally don't see any issues with having a dependency on pre-release code since starfish is not 1.0.

**Comment by kne42** [comment]
That's true – it's not necessary to follow best practice on pre-alpha projects, especially if you don't have many users. Ultimately it's up to your discretion. However, I will warn you that installing from source may result in certain problems/slower installation since the user will be building the wheels from scratch. For example, `scikit-image` requires `cython` to be installed prior to its installation in order to build its C files.

**Comment by ttung** [comment]
Yup, that was my [first question](https://spacetx.slack.com/archives/CAR91U354/p1550207232183100) :)

**Comment by ttung** [comment]
So yeah, monkey patch it is. :)

**Comment by joshmoore** [comment]
In working on gh-1059, I ran into a couple of alternatives for version pinning. I've kept any of that out of gh-1059 (despite the bullet point "run extended check_requirements" in gh-761) but wanted to list them in case solving both together would point to changes in gh-1059:

 * https://github.com/jazzband/pip-tools
 * https://github.com/sdispater/poetry (can also replace setuptools)
 * https://github.com/pypa/pipfile
